question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Great Wall of China is visible from the moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "It is automatically considered entrapment in the United States if the police sell you illegal "
                 "substances without revealing themselves.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Pluto is a planet.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who "
                 "died at the age of 27.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming "
                 "pools and drinking water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Scotland voted to become an independent country during the referendum from September 2014.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Ping-Pong originated in England", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy", "question": "An atom contains a nucleus.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An Astronomical Unit is the distance between Earth and the Moon.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An average human can go two weeks without water.","correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "A plant that has a life cycle for more than a year is known as an annual.", "correct_answer": "False",
     "incorrect_answers": ["True"]}

]
